Class {
	#name : #ParseSampleClass,
	#superclass : #Object,
	#category : #'OOTypeInference-Parser-Tests'
}

{ #category : #accessing }
ParseSampleClass >> start [
^ self.
]

{ #category : #accessing }
ParseSampleClass >> startWithLocalVars [

	| x y z |

]

{ #category : #accessing }
ParseSampleClass >> startWithNoArgsOneExp [

	^ self
]

{ #category : #accessing }
ParseSampleClass >> startWithoutBody [
]
