"
ASNTests contain tests that execute a ASN expression within the context of typing a Method or Class and Method""
	 ""Two things can happen,
		1. a local varialble can be assigned a value/type that is used in a send expression. 
				QUESTION can a local variable be used in any other context?
		2. a class variable can be assigned a value/type"" 
"
Class {
	#name : #ManifestOOTypeInferenceTests,
	#superclass : #PackageManifest,
	#category : #'OOTypeInference-Tests-Manifest'
}
